global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:7777']
    metrics_path: '/'

  - job_name: 'publisher'
    static_configs:
      - targets: ['publisher:2112']

  - job_name: 'subscriber'
    static_configs:
      - targets: ['subscriber:2112']
